social:
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: GitHub
    link: https://github.com/61hhh
    icon: icon-github-line
    color: "#6e5494"
  - name: E-Mail
    link: mailto:salute61@163.com
    icon: icon-mail-line
    color: "#8E71C1"

# UI
banner:
  enable: true
  title: 不羁的风
  border: true
  cloud:
    enable: true
    color: "grey"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# 背景图
bg_image:
  enable: true
  url: /images/day.jpg # https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/lightBG.jpg
  dark: /images/night.jpg #https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/darkBG.jpg
  # blur: 10px
  opacity: 1

# Extra links 改为推荐
pages:
  - name: 61nav
    url: https://61navigator.vercel.app/
    icon: icon-genderless-line
    color: "#81D8D0"

# 显示文章访问量和评论量.
# You can visit https://www.leancloud.cn to get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id:  TdBU4bxll43AQFzEBGhrVRQy-MdYXbMMI # <your app id>
  app_key:  MMJsM8cWGY7bEm704Dl6269n # <your app key>

# https://waline.js.org/
waline:
  enable: true
  serverURL: waline-server-sepia.vercel.app # https://your-domain.vercel.app
  # visitor: false
  # display comment count
  comment: true

# Google分析
google_analytics:
  enable: true
  # GA4 采用新的GA4取代原有的通用应用
  id: G-TGD6JKV63N

# 跳过Hexo的渲染
skip_render:
  - README.md
  - baidu_verify_iy61Ytn0Lm.html
  - googled2e2ddbb7fc7dc7e.html

# SEO
# https://ziyuan.baidu.com/linksubmit/index
baidu_push: true

# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true

# Favicon
# ---------------
favicon: /images/iconMe.svg

# Sidebar Avatar
avatar:
  enable: true
  url: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/iconMe.png

# 打赏
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: 支付宝
      path: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/AliPay.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: 微信支付
      path: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/WechatPay.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line